// <auto-generated />
using System;
using BlazorAcademyHW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAcademyHW.Migrations
{
    [DbContext(typeof(BlazorAcademyHWContext))]
    [Migration("20260513082412_mssql.local_migration_569")]
    partial class mssqllocal_migration_569
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAcademyHW.Models.Directions", b =>
                {
                    b.Property<byte>("direction_id")
                        .HasColumnType("tinyint");

                    b.Property<string>("direction_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Disciplines", b =>
                {
                    b.Property<short>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("tinyint");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Groups", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("group_id"));

                    b.Property<byte?>("direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("group_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.GroupsDay", b =>
                {
                    b.Property<int>("groups_day_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("groups_day_id"));

                    b.Property<int>("day_id")
                        .HasColumnType("int");

                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.HasKey("groups_day_id");

                    b.HasIndex("day_id");

                    b.HasIndex("group_id");

                    b.ToTable("GroupsDays");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Students", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateOnly?>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stud_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.StudyDay", b =>
                {
                    b.Property<int>("day_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("day_id"));

                    b.Property<string>("day_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("day_order")
                        .HasColumnType("int");

                    b.Property<string>("day_short")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("day_id");

                    b.ToTable("StudyDays");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.TeacherDiscipline", b =>
                {
                    b.Property<int>("teacher_discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacher_discipline_id"));

                    b.Property<short>("discipline_id")
                        .HasColumnType("smallint");

                    b.Property<short>("teacher_id")
                        .HasColumnType("smallint");

                    b.HasKey("teacher_discipline_id");

                    b.HasIndex("discipline_id");

                    b.HasIndex("teacher_id");

                    b.ToTable("TeacherDisciplines");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Teachers", b =>
                {
                    b.Property<short>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("teacher_id"));

                    b.Property<DateOnly?>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("work_since")
                        .HasColumnType("date");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.GroupsDay", b =>
                {
                    b.HasOne("BlazorAcademyHW.Models.StudyDay", "StudyDay")
                        .WithMany()
                        .HasForeignKey("day_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAcademyHW.Models.Groups", "Group")
                        .WithMany("GroupsDays")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("StudyDay");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.TeacherDiscipline", b =>
                {
                    b.HasOne("BlazorAcademyHW.Models.Disciplines", "Discipline")
                        .WithMany("TeacherDisciplines")
                        .HasForeignKey("discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAcademyHW.Models.Teachers", "Teacher")
                        .WithMany("TeacherDisciplines")
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Disciplines", b =>
                {
                    b.Navigation("TeacherDisciplines");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Groups", b =>
                {
                    b.Navigation("GroupsDays");
                });

            modelBuilder.Entity("BlazorAcademyHW.Models.Teachers", b =>
                {
                    b.Navigation("TeacherDisciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
